### ISSUE TITLE
Decide on project idea:

### ISSUE THREAD

**Issue by JoGorska** [adowlin/spookathon-team7#8]
Concept
Front-End or Full-Stack?

**Comment by SiJiL82** [comment]
Site will be a copy of the attached poem, with each verse being 1 full screen section on the page.
User will scroll / click to transition to the next verse, with animated effects happening when they do.
![image](https://user-images.githubusercontent.com/65114782/137384146-02c78017-a2d5-46dc-917c-1d532cd00fa1.png)
